import { expect, test } from "@playwright/test";

test("admin can publish, update, disable and remove a product", async ({ page }) => {
  const productName = `Producto QA ${Date.now()}`;
  if (!process.env.ADMIN_EMAIL || !process.env.ADMIN_PASSWORD) throw new Error("Admin test credentials are not configured.");
  await page.goto("/admin/login");
  await page.getByLabel("Correo").fill(process.env.ADMIN_EMAIL);
  await page.getByLabel("Contraseña").fill(process.env.ADMIN_PASSWORD);
  await page.getByRole("button", { name: "Entrar al panel" }).click();
  await expect(page).toHaveURL(/\/admin$/);
  await page.getByRole("button", { name: "Productos", exact: true }).click();
  await page.getByLabel("Nombre").fill(productName);
  await page.getByLabel("Precio RD$").fill("350");
  await page.getByLabel("Descripción breve").fill("Producto temporal para verificar el flujo completo.");
  await page.getByLabel("Descripción completa").fill("Preparación temporal creada por la prueba de integración de administración.");
  await page.getByLabel(/Ingredientes/).fill("Maíz, Ají, Hierbas");
  await page.getByRole("button", { name: "Publicar producto" }).click();
  await expect(page.getByText("Producto creado y publicado.")).toBeVisible();
  await page.getByPlaceholder("Buscar plato").fill(productName);
  await expect(page.getByText(productName, { exact: true }).last()).toBeVisible();
  await page.getByRole("button", { name: `Editar ${productName}` }).click();
  await page.getByLabel("Precio RD$").fill("390");
  await page.getByRole("button", { name: "Guardar producto" }).click();
  await expect(page.getByText("Producto actualizado y publicado.")).toBeVisible();
  await page.getByPlaceholder("Buscar plato").fill(productName);
  await page.getByRole("button", { name: "Disponible" }).click();
  await expect(page.getByText("Producto marcado como no disponible.")).toBeVisible();
  page.on("dialog", (dialog) => dialog.accept());
  await page.getByPlaceholder("Buscar plato").fill(productName);
  await page.getByRole("button", { name: `Eliminar ${productName}` }).click();
  await expect(page.getByText("Producto eliminado.")).toBeVisible();
});
