ALTER TABLE "Restaurant" ADD COLUMN "city" TEXT NOT NULL DEFAULT 'Quito';
ALTER TABLE "Restaurant" ADD COLUMN "countryCode" TEXT NOT NULL DEFAULT 'EC' CHECK ("countryCode" = 'EC');
ALTER TABLE "Restaurant" ADD COLUMN "latitude" REAL NOT NULL DEFAULT -0.220164 CHECK ("latitude" BETWEEN -90 AND 90);
ALTER TABLE "Restaurant" ADD COLUMN "longitude" REAL NOT NULL DEFAULT -78.512327 CHECK ("longitude" BETWEEN -180 AND 180);
